version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      #      - run: yes | sdkmanager --licenses || exit 0
      #
      #      - run: yes | sdkmanager --update || exit 0
      - run:
          name: Run Presentation Module Unit Tests
          command: ./gradlew :app:test
      - store_artifacts:
          path: app/build/reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Run Domain Module Unit Tests
          command: ./gradlew :domain:test
      - store_artifacts:
          path: domain/build/reports
      - store_test_results:
          path: domain/build/test-results
      - run:
          name: Run Data Module Unit Tests
          command: ./gradlew :data:testDebugUnitTest
      - store_artifacts:
          path: data/build/reports
      - store_test_results:
          path: data/build/test-results
      - run:
          name: Run Build
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results